<<<<<<< HEAD
<<<<<<< HEAD
title: Rainbow Colours Family Day Care
description: " At Rainbow Colours Family Day Care, we understand the importance
  of a supportive and nurturing environment for your little ones. Our family
  daycare is designed to be a haven where children flourish through play,
  exploration, and genuine care.                               "
authorName: Sapna Yadav
authorImage: /images/uploads/sapnayadav.jpeg
items:
  - emailAddress: rainbowcoloursfamilydaycare@gmail.com
    phoneNumber: 0437 982 299
    Address: 26 Parsons Road, Bardia, NSW, 2565
googleAnalyticsId: "2312"
=======
=======
websiteTitle: Rainbow Colours Family Day Care
websiteDescription: At Rainbow Colours Family Day Care, we understand the importance of a supportive and nurturing environment for your little ones. Our family daycare is designed to be a haven where children flourish through play, exploration, and genuine care.
>>>>>>> ee19e1e (improved website)
googleAnalyticsId: UA-
phoneNumber: 0437 982 299
emailAddress: rainbowcoloursfamilydaycare@gmail.com
address: 26 Parsons Road, Bardia, NSW, 2565
>>>>>>> 00593a7 (improved site)
