backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "settings"
    label: "Website Settings"
    description: "Configure default settings here"
    files:
      - label: "Edit Settings"
        name: "settings"
        file: "_data/settings.yml"
        fields:
          - {
              label: "Website title",
              name: "websiteTitle",
              widget: "string",
              default: "Sapna Yadav",
            }
          - {
              label: "Website description",
              name: "websiteDescription",
              widget: "string",
              default: "Sapna Yadav",
            }
          - { label: "Email Address", name: "emailAddress", widget: "string" }
          - { label: "Phone Number", name: "phoneNumber", widget: "string" }
          - { label: "Address", name: "address", widget: "string" }
          - {
              label: "Google analytics id",
              name: "googleAnalyticsId",
              widget: "string",
            }
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - label: "Homepage"
        name: "Homepage"
        file: "_data/homepage.yml"
        fields:
          - {
              label: "Hero Copy",
              name: "heroCopy",
              widget: "string",
              default: At Rainbow Colours Family Day Care,
              we understand the importance of a supportive and nurturing environment for your little ones. Our family daycare is designed to be a haven where children flourish through play,
              exploration,
              and genuine care.,
            }
