backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "settings"
    label: "Website Settings"
    description: "Configure default settings here"
    files:
      - label: "Edit Settings"
        name: "settings"
        file: "_data/settings.yml"
        fields:
          - {
              label: "Website title",
              name: "websiteTitle",
              widget: "string",
              default: "Sapna Yadav",
            }
          - {
              label: "Website description",
              name: "websiteDescription",
              widget: "string",
              default: "Sapna Yadav",
            }
          - { label: "Email Address", name: "emailAddress", widget: "string" }
          - { label: "Phone Number", name: "phoneNumber", widget: "string" }
          - { label: "Address", name: "address", widget: "string" }
  - name: "section"
    label: "Sections"
    editor:
      preview: false
    files:
      - label: "Hero Panel"
        name: "Hero"
        file: "_data/hero.yml"
        fields:
          - {
              label: "Hero Panel",
              name: "heroCopy",
              widget: "markdown",
              default: At Rainbow Colours Family Day Care,
              we understand the importance of a supportive and nurturing environment for your little ones. Our family daycare is designed to be a haven where children flourish through play,
              exploration,
              and genuine care.,
            }
      - label: "Gallery"
        name: "gallery"
        file: "_data/gallery.yml"
        widget: "list"
        fields:
          - label: Gallery Images
            name: galleryImages
            widget: list
            fields:
              - { label: Image, name: image, widget: image }
              - { label: Image Alt Text, name: altText, widget: string }
      - label: "About"
        name: "items"
        file: "_data/about.yml"
        widget: "list"
        fields:
          - label: panel
            name: Panel
            widget: list
            fields:
              - { label: Panel Heading, name: panelHeading, widget: string }
              - {
                  label: Panel Colour,
                  name: panelColor,
                  widget: list,
                  default: "bg-pallet-color-1",
                }
              - { label: Panel Icon, name: panelIcon, widget: string }
              - {
                  label: Panel Content Heading,
                  name: panelContentHeading,
                  widget: text,
                }
              - { label: Panel Content, name: panelContent, widget: markdown }
              - { label: Image, name: image, widget: image }
              - { label: Image Alt Text, name: altText, widget: string }
